SecRule REQUEST_FILENAME "@beginsWith /portal/phishing-emails/" "id:1000100,phase:1,pass,t:none,nolog,chain"
    SecRule REQUEST_METHOD "@streq POST" "t:none,ctl:ruleRemoveTargetByTag=attack-xss;ARGS:phishing-email-body"

SecRule REQUEST_FILENAME "@beginsWith /portal/campaigns/" "id:1001001,phase:1,pass,t:none,nolog,chain"
    SecRule REQUEST_METHOD "@streq POST" "t:none,ctl:ruleRemoveTargetById=932125;ARGS:campaign-recipients,ctl:ruleRemoveTargetById=932235;ARGS:campaign-recipients,ctl:ruleRemoveTargetById=942240;ARGS:campaign-recipients"